services:

  database:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: dwd_secret
    volumes:
      - ./database:/var/lib/postgresql
    container_name: dwd_database
  
  redis:
    image: redis:alpine
    restart: unless-stopped
    container_name: dwd_redis

  backend:
    image: dwd_backend:latest
    build: ./backend
    restart: unless-stopped
    depends_on:
      - database
      - redis
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=database
      - POSTGRES_PASSWORD=dwd_secret
    container_name: dwd_backend

  frontend:
    image: dwd_frontend:latest
    build: ./frontend
    ports:
      - "80:8080"
    container_name: dwd_frontend
