services:

  redis:
    image: redis:alpine

  backend:
    image: backend:latest
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - REQUEST_ORIGIN=http://localhost:5000
      - REDIS_HOST=redis
    container_name: backend
    restart: unless-stopped

  frontend:
    image: frontend:latest
    build: ./frontend
    ports:
      - "5000:5000"
    environment:
      - ENV REACT_APP_BACKEND_URL=http://localhost:8080
    container_name: frontend
